### ISSUE TITLE
Can't install via Composer

### ISSUE THREAD

**Issue by bruno-rodrigues** [iamkirkbater/soft-deletes#1]
When I try to: 

`composer require kirkbater/soft-deletes`

I get the following error:

```
[InvalidArgumentException]                                                                                                            
  Could not find package kirkbater/soft-deletes at any version for your minimum-stability (stable). Check the package spelling or your  
   minimum-stability 
```

Am I missing something? 
Thank you for your package.

**Comment by bruno-rodrigues** [comment]
Fixed, I had to run `composer require kirkbater/soft-deletes @dev` to get it working.

**Comment by iamkirkbater** [comment]
I've tagged the current master as 1.0 and updated Packagist, so if you want to change from dev-master to that feel free to.
