### ISSUE TITLE
kirkbater folder name in src should have its first letter capitalized

### ISSUE THREAD

**Issue by plopinou** [iamkirkbater/soft-deletes#2]
Thanks for your package ! That saved me some time in my testing.

I had a problem after requiring it thought : 

```
PHP Fatal error:  Trait 'SoftDeletes' not found in /srv/www/myproject/tests/MyTest.php
```

The solution was really simple : capitalizing the first letter of Kirkbater

```
mv vendor/kirkbater/soft-deletes/src/kirkbater/ vendor/kirkbater/soft-deletes/src/Kirkbater/
```

Just to let you know in case you want to correct it :)

**Comment by iamkirkbater** [comment]
Thanks for bringing this up.  Sorry I couldn't get to it sooner!
